import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "@/components/provider/provider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Zuela Amazonica",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  // title: "Tienda Online | Calzado Amazonica",
  title: {
    template: "%s Tienda online | Zuela Amazonica",
    default: "Home - Zuela Amazonica"
  },
  description: "Compra los mejores zapatos en línea con Calzado Amazonas",
  keywords: ["calzado", "tienda online", "zapatos", "moda"],
  authors: [{ name: "Wildor Programador" }],
  creator: "Wildor Programador",
  themeColor: "#ffffff",
  openGraph: {
    title: "Calzado Amazonica",
    description: "Compra los mejores zapatos en línea",
    url: "https://calzado-amazonico.vercel.app/",
    siteName: "Calzado Amazonas",
    images: [
      {
        url: "/og-image.png",
        width: 1200,
        height: 630,
      },
    ],
    locale: "es_PE",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Zuela Amazonica",
    description: "Compra los mejores zapatos en línea",
    images: ["/og-image.png"],
  },
  verification: {
    google: "google28b76eb64ad06fed",
  },
  // verification: {
  //   google: "11diTBZ21KUh3VX80X2YflTHrYn0QrLkGT6csg8roC4",
  // },
};
{/* <meta name="google-site-verification" content="11diTBZ21KUh3VX80X2YflTHrYn0QrLkGT6csg8roC4" /> */}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/zuela-amazonica.ico" />
        {/* <script src="https://sandbox-checkout.izipay.pe/payments/v1/js/index.js" defer></script>
        <script src="https://static.micuentaweb.pe/static/js/authenticate-client/V1.0/kr-authenticate.umd.js" defer></script> */}

        {/* SCRIPT DE CULQUI */}
        {/* <script src="https://js.culqi.com/checkout-js" defer></script> */}

      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
